/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoze;

//VERSÃO UTILIZADA: NetBeans IDE 17
//Aluno: Roger Yoshiaki Motoyama / ra:2418355
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Roger
 */
public class TelaBusca extends javax.swing.JFrame {
    private static TelaBusca telaBusca;

    private TelaBusca() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public static TelaBusca getTelaBusca() {
        if (telaBusca == null) {
            telaBusca = new TelaBusca();
        }
        return telaBusca;
    }
    /**
     * Creates new form TelaBusca
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAlimento = new javax.swing.ButtonGroup();
        botaoHamb = new javax.swing.JRadioButton();
        botaoPizza = new javax.swing.JRadioButton();
        botaoPastel = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmpIdVenda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(865, 635));

        buttonGroupAlimento.add(botaoHamb);
        botaoHamb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoHamb.setText("Hamburguer");

        buttonGroupAlimento.add(botaoPizza);
        botaoPizza.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoPizza.setText("Pizza");

        buttonGroupAlimento.add(botaoPastel);
        botaoPastel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoPastel.setText("Pastel");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Busca de vendas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Por favor selecione por qual alimento deseja buscar:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Agora, digite o ID da venda e clique no botão de busca!");

        jButton1.setText("Busca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID Venda", "Cliente", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoHamb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoPastel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(cmpIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botaoPizza))
                    .addComponent(botaoHamb)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(botaoPastel)))
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmpIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        setBounds(0, 0, 900, 635);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (botaoHamb.isSelected()) {
            buscaIdHamb();
        } else if(botaoPastel.isSelected()){
            buscaIdPastel();
        } else if(botaoPizza.isSelected()){
            buscaIdPizza();
        } else{
            JOptionPane.showMessageDialog(null, "Por favor selecione um dos tipos de alimento para busca", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    private void buscaIdHamb() {
        Hamburguer h = new Hamburguer();
        try {
            h.getVenda().setIdVenda(Integer.parseInt(cmpIdVenda.getText()));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Por favor, campo de ID venda é permitido apenas números inteiros", "Erro de formato de ID", JOptionPane.ERROR_MESSAGE);
            return;
        }
        h = BD.getBD().consultaIdHamb(h);
        if (h != null) {
            JOptionPane.showMessageDialog(null, "ID ENCONTRADO !", "Busca com sucesso", JOptionPane.INFORMATION_MESSAGE);
            DefaultTableModel modeloTabela = (DefaultTableModel) tabela.getModel();
            Object[] linha = {
                h.getVenda().getIdVenda(),
                h.getVenda().getNomeCliente(),
                h.getVenda().getValorTotal(),
            };
            modeloTabela.addRow(linha);

        } else {
            JOptionPane.showMessageDialog(null, "Nenhum hamburguer cadastrado neste id", "Busca nao encontrada", JOptionPane.ERROR_MESSAGE);
        }
    }
     private void buscaIdPizza() {
        Pizza pizza = new Pizza();
        try {
            pizza.getVenda().setIdVenda(Integer.parseInt(cmpIdVenda.getText()));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Por favor, campo de ID venda é permitido apenas números inteiros", "Erro de formato de ID", JOptionPane.ERROR_MESSAGE);
            return;
        }
        pizza = BD.getBD().consultaIdPizza(pizza);
        if (pizza != null) {
            JOptionPane.showMessageDialog(null, "ID ENCONTRADO !", "Busca com sucesso", JOptionPane.INFORMATION_MESSAGE);
            DefaultTableModel modeloTabela = (DefaultTableModel) tabela.getModel();
            Object[] linha = {
                pizza.getVenda().getIdVenda(),
                pizza.getVenda().getNomeCliente(),
                pizza.getVenda().getValorTotal(),
            };
            modeloTabela.addRow(linha);

        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma pizza cadastrado neste id", "Busca nao encontrada", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     private void buscaIdPastel() {
        Pastel pastel = new Pastel();
        try {
            pastel.getVenda().setIdVenda(Integer.parseInt(cmpIdVenda.getText()));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Por favor, campo de ID venda é permitido apenas números inteiros", "Erro de formato de ID", JOptionPane.ERROR_MESSAGE);
            return;
        }
        pastel = BD.getBD().consultaIdPastel(pastel);
        if (pastel != null) {
            JOptionPane.showMessageDialog(null, "ID ENCONTRADO !", "Busca com sucesso", JOptionPane.INFORMATION_MESSAGE);
            DefaultTableModel modeloTabela = (DefaultTableModel) tabela.getModel();
            Object[] linha = {
                pastel.getVenda().getIdVenda(),
                pastel.getVenda().getNomeCliente(),
                pastel.getVenda().getValorTotal(),
            };
            modeloTabela.addRow(linha);

        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma pastel cadastrado neste id", "Busca nao encontrada", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botaoHamb;
    private javax.swing.JRadioButton botaoPastel;
    private javax.swing.JRadioButton botaoPizza;
    private javax.swing.ButtonGroup buttonGroupAlimento;
    private javax.swing.JTextField cmpIdVenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
